### ISSUE TITLE
batch_iter() causes BrokenProcessPool

### ISSUE THREAD

**Issue by repsej112** [minerllabs/minerl#354]
The error prints when i run the loop(not when i instantiate the data)

```ENV_NAME = "MineRLTreechopVectorObf-v0" 
data = minerl.data.make(ENV_NAME)

for current_state, action, reward, next_state, done in data.batch_iter(batch_size=1, num_epochs=1, seq_len=32):

    # Print the POV @ the first step of the sequence
    print(current_state['pov'][0])

    # Print the final reward pf the sequence!
    print(reward[-1])

    # Check if final (next_state) is terminal.
    print(done[-1])

    # ... do something with the data.
    print("At the end of trajectories the length", "can be < max_sequence_len", len(reward))
```

100%|██████████| 209/209 [00:00<00:00, 9502.54it/s]
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\Jesper\Anaconda3\envs\minebot\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Jesper\Anaconda3\envs\minebot\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jesper\Anaconda3\envs\minebot\lib\site-packages\minerl\data\util\__init__.py", line 201, in _ordered_job_streamer
    raise future.exception()
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by repsej112** [comment]
Fixed! had to place the code inside an `if __name__ == "__main__"'

**Comment by JACKHAHA363** [comment]
I have the similiar problem, but the fix does not work for me. Can I know about your system/python version?

**Comment by repsej112** [comment]
> I have the similiar problem, but the fix does not work for me. Can I know about your system/python version?

I use python 3.7.6 in a Conda environment, windows 10

**Comment by MadcowD** [comment]
@JACKHAHA363  was this resolved for you?

**Comment by JACKHAHA363** [comment]
Actually the fix I previously posted does not solve the issue.
